#### Transpose matrix

In [1]:
import numpy as np

In [6]:
var = np.matrix([[1,2,3],[5,6,7]])
print(var)
print()


print(np.transpose(var))
print()
print("another shortcutway")
print(var.T)

[[1 2 3]
 [5 6 7]]

[[1 5]
 [2 6]
 [3 7]]

another shortcutway
[[1 5]
 [2 6]
 [3 7]]


### swapaxes

In [8]:
print(np.swapaxes(var,0,1))

[[1 5]
 [2 6]
 [3 7]]


### square matrix

In [9]:
var2 = ([[1,2],[3,4]])
print(var2)
print()

print(np.swapaxes(var2,0,1))

[[1, 2], [3, 4]]

[[1 3]
 [2 4]]


### inverse matrix

In [10]:
# A power -1

In [20]:
var3 = np.matrix([[1,2],[3,4]])
print(var3) 
print()


print("inverse matrix :",np.linalg.inv(var3))

[[1 2]
 [3 4]]

inverse matrix : [[-2.   1. ]
 [ 1.5 -0.5]]


### power matrix

In [19]:
#A  square = AA

In [28]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print("power matrix : ",np.linalg.matrix_power(var4,2))
print("power matrix n=0 ,identity matrix: ",np.linalg.matrix_power(var4,0))
print("power matrix= inverse * -ive power : ",np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

power matrix :  [[ 7 10]
 [15 22]]
power matrix n=0 ,identity matrix:  [[1 0]
 [0 1]]
power matrix= inverse * -ive power :  [[ 5.5  -2.5 ]
 [-3.75  1.75]]


### determinent of matrix 

In [30]:
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()

print("determinent : ",np.linalg.det(var5))

[[1 2]
 [3 4]]

determinent :  -2.0000000000000004
